# print('This is a learning for inputs and datatypes')
# name = str(input('Please Enter your name: '))
# age = int(input('Please enter your age: '))
# email = str(input('Please enter your email: '))
# phonenumber = int(input('Please enter your phone number: '))
# password = str(input('Please enter a password: '))

# print('your profile is as follows')
# print('Your name is' + name)
# print('Your age is' + str(age))
# print('your email is' + email)
# print('your phone number is' + str(phonenumber))
# print('your password is' + password)
# print('you will be' + str(age+1) + 'in a year')
print('Enter name')
name = input()
name2 = float(input())

print('The round is' + str(round(name2)))
print('The length is' + str(len(name)))
